---
version: 1
disable_existing_loggers: False

formatters:
    simple:
        (): pythonjsonlogger.jsonlogger.JsonFormatter
        format: "%(levelname)s - %(module)s - %(filename)s - %(funcName)s - %(created)s - %(asctime)s - %(message)s"

handlers:
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [debug_file_handler]